#!/usr/bin/env bash

###################################################################
# STACKORED GENERATOR (SHELL VERSION)
# PHP olmadan Docker Compose dosyalarını oluşturur
###################################################################

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

GREEN='\033[0;32m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo -e "${BLUE}[INFO]${NC} Stackored Generator Starting..."

###################################################################
# .env DOSYASINI YÜKLE
###################################################################
if [ ! -f "$ROOT_DIR/.env" ]; then
    echo "[ERROR] .env file not found!"
    exit 1
fi

echo -e "${BLUE}[INFO]${NC} Loading environment variables..."
set -a
source "$ROOT_DIR/.env"
set +a

###################################################################
# HELPER FUNCTIONS
###################################################################

# Check if module is enabled
is_enabled() {
    local var_name=$1
    local var_value="${!var_name}"
    local lower_value=$(echo "$var_value" | tr '[:upper:]' '[:lower:]')
    [[ "$lower_value" == "true" ]]
}

# Replace template variables
render_template() {
    local template_file=$1
    local output=""
    
    if [ -f "$template_file" ]; then
        output=$(cat "$template_file")
        
        # Replace common variables
        output="${output//\{\{ DOCKER_DEFAULT_NETWORK \}\}/$DOCKER_DEFAULT_NETWORK}"
        output="${output//\{\{ MYSQL_VERSION \}\}/$MYSQL_VERSION}"
        output="${output//\{\{ REDIS_VERSION \}\}/$REDIS_VERSION}"
        output="${output//\{\{ POSTGRES_VERSION \}\}/$POSTGRES_VERSION}"
        output="${output//\{\{ MONGO_VERSION \}\}/$MONGO_VERSION}"
        output="${output//\{\{ MEMCACHED_VERSION \}\}/$MEMCACHED_VERSION}"
        output="${output//\{\{ ELASTICSEARCH_VERSION \}\}/$ELASTICSEARCH_VERSION}"
        output="${output//\{\{ RABBITMQ_VERSION \}\}/$RABBITMQ_VERSION}"
        output="${output//\{\{ KAFKA_VERSION \}\}/$KAFKA_VERSION}"
        output="${output//\{\{ NATS_VERSION \}\}/$NATS_VERSION}"
        output="${output//\{\{ MAILHOG_VERSION \}\}/$MAILHOG_VERSION}"
        output="${output//\{\{ TRAEFIK_EMAIL \}\}/$TRAEFIK_EMAIL}"
        
        echo "$output"
    fi
}

###################################################################
# CREATE BASE stackored.yml
###################################################################
echo -e "${BLUE}[INFO]${NC} Generating stackored.yml (base compose)..."

cat > "$ROOT_DIR/stackored.yml" << 'EOFBASE'
version: "3.9"

###################################################################
# STACKORED - BASE COMPOSE (Traefik & Network)
# Auto-generated by Stackored Generator
###################################################################

services:

  traefik:
    image: traefik:latest
    container_name: stackored-traefik
    restart: unless-stopped
    
    command:
      - "--api.dashboard=true"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedByDefault=false"
      - "--providers.file.directory=/etc/traefik/dynamic"
      - "--providers.file.watch=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
    
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"  # Dashboard
    
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./core/traefik/dynamic:/etc/traefik/dynamic:ro"
    
    networks:
      - stackored-net

networks:
  stackored-net:
    name: stackored-net
    driver: bridge
    driver_opts:
      com.docker.network.bridge.enable_icc: "true"
      com.docker.network.bridge.enable_ip_masquerade: "true"
    ipam:
      driver: default
      config:
        - subnet: "172.30.0.0/16"
          gateway: "172.30.0.1"

EOFBASE

###################################################################
# CREATE DYNAMIC docker-compose.dynamic.yml
###################################################################
echo -e "${BLUE}[INFO]${NC} Generating docker-compose.dynamic.yml..."

cat > "$ROOT_DIR/docker-compose.dynamic.yml" << EOFDYNAMIC
version: "3.9"

###################################################################
# STACKORED - DYNAMIC COMPOSE
# Auto-generated based on enabled modules in .env
###################################################################

services:

EOFDYNAMIC

###################################################################
# SCAN AND ADD PROJECTS
###################################################################
echo -e "${BLUE}[INFO]${NC} Scanning projects..."

PROJECTS_DIR="$ROOT_DIR/projects"
if [ -d "$PROJECTS_DIR" ]; then
    for project_dir in "$PROJECTS_DIR"/*; do
        if [ -d "$project_dir" ]; then
            project_name=$(basename "$project_dir")
            config_file="$project_dir/stackored.json"
            
            if [ -f "$config_file" ]; then
                echo -e "${BLUE}[INFO]${NC} Adding project: $project_name"
                
                # Read JSON config using grep and sed (simple parsing)
                domain=$(grep -o '"domain"[[:space:]]*:[[:space:]]*"[^"]*"' "$config_file" | sed 's/.*"\([^"]*\)".*/\1/')
                php_version=$(grep -o '"version"[[:space:]]*:[[:space:]]*"[^"]*"' "$config_file" | sed 's/.*"\([^"]*\)".*/\1/' | head -1)
                webserver=$(grep -o '"webserver"[[:space:]]*:[[:space:]]*"[^"]*"' "$config_file" | sed 's/.*"\([^"]*\)".*/\1/')
                doc_root=$(grep -o '"document_root"[[:space:]]*:[[:space:]]*"[^"]*"' "$config_file" | sed 's/.*"\([^"]*\)".*/\1/')
                
                # Defaults
                [ -z "$domain" ] && domain="${project_name}.${TLD_SUFFIX}"
                [ -z "$php_version" ] && php_version="$DEFAULT_PHP_VERSION"
                [ -z "$webserver" ] && webserver="$DEFAULT_WEBSERVER"
                [ -z "$doc_root" ] && doc_root="$DEFAULT_DOCUMENT_ROOT"
                
                # Add PHP-FPM container
                cat >> "$ROOT_DIR/docker-compose.dynamic.yml" << EOF
  ${project_name}-php:
    image: php:${php_version}-fpm-alpine
    container_name: stackored-${project_name}-php
    restart: unless-stopped
    volumes:
      - ./projects/${project_name}:/var/www/html
    working_dir: /var/www/html
    networks:
      - stackored-net

EOF

                # Add Nginx container
                cat >> "$ROOT_DIR/docker-compose.dynamic.yml" << EOF
  ${project_name}-web:
    image: nginx:alpine
    container_name: stackored-${project_name}-web
    restart: unless-stopped
    volumes:
      - ./projects/${project_name}:/var/www/html
      - ./projects/${project_name}/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - ${project_name}-php
    networks:
      - stackored-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${project_name}.rule=Host(\`${domain}\`)"
      - "traefik.http.routers.${project_name}.entrypoints=web"
      - "traefik.http.services.${project_name}.loadbalancer.server.port=80"

EOF
                
                # Create nginx.conf if not exists
                nginx_conf="$project_dir/nginx.conf"
                if [ ! -f "$nginx_conf" ]; then
                    cat > "$nginx_conf" << 'NGINX_EOF'
server {
    listen 80;
    server_name _;
    root /var/www/html/public;
    index index.php index.html;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        fastcgi_pass stackored-PROJECT_NAME-php:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
    }

    location ~ /\.ht {
        deny all;
    }
}
NGINX_EOF
                    # Replace PROJECT_NAME placeholder
                    sed -i '' "s/PROJECT_NAME/${project_name}/g" "$nginx_conf"
                fi
            fi
        fi
    done
fi

###################################################################
# ADD ENABLED SERVICES
###################################################################

# MySQL
if is_enabled "ENABLE_MYSQL"; then
    echo -e "${BLUE}[INFO]${NC} Adding MySQL ${MYSQL_VERSION}..."
    cat >> "$ROOT_DIR/docker-compose.dynamic.yml" << EOF
  mysql:
    image: mysql:${MYSQL_VERSION}
    container_name: stackored-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: stackored
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - stackored-net

EOF
fi

# Redis
if is_enabled "ENABLE_REDIS"; then
    echo -e "${BLUE}[INFO]${NC} Adding Redis ${REDIS_VERSION}..."
    cat >> "$ROOT_DIR/docker-compose.dynamic.yml" << EOF
  redis:
    image: redis:${REDIS_VERSION}-alpine
    container_name: stackored-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - stackored-net

EOF
fi

# PostgreSQL
if is_enabled "ENABLE_POSTGRES"; then
    echo -e "${BLUE}[INFO]${NC} Adding PostgreSQL ${POSTGRES_VERSION}..."
    cat >> "$ROOT_DIR/docker-compose.dynamic.yml" << EOF
  postgres:
    image: postgres:${POSTGRES_VERSION}-alpine
    container_name: stackored-postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: stackored
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - stackored-net

EOF
fi

# MongoDB
if is_enabled "ENABLE_MONGO"; then
    echo -e "${BLUE}[INFO]${NC} Adding MongoDB ${MONGO_VERSION}..."
    cat >> "$ROOT_DIR/docker-compose.dynamic.yml" << EOF
  mongo:
    image: mongo:${MONGO_VERSION}
    container_name: stackored-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - stackored-net

EOF
fi

# Memcached
if is_enabled "ENABLE_MEMCACHED"; then
    echo -e "${BLUE}[INFO]${NC} Adding Memcached ${MEMCACHED_VERSION}..."
    cat >> "$ROOT_DIR/docker-compose.dynamic.yml" << EOF
  memcached:
    image: memcached:${MEMCACHED_VERSION}-alpine
    container_name: stackored-memcached
    restart: unless-stopped
    ports:
      - "11211:11211"
    networks:
      - stackored-net

EOF
fi

# RabbitMQ
if is_enabled "ENABLE_RABBITMQ"; then
    echo -e "${BLUE}[INFO]${NC} Adding RabbitMQ ${RABBITMQ_VERSION}..."
    cat >> "$ROOT_DIR/docker-compose.dynamic.yml" << EOF
  rabbitmq:
    image: rabbitmq:${RABBITMQ_VERSION}-management-alpine
    container_name: stackored-rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"  # Management UI
    networks:
      - stackored-net

EOF
fi

# Elasticsearch
if is_enabled "ENABLE_ELASTICSEARCH"; then
    echo -e "${BLUE}[INFO]${NC} Adding Elasticsearch ${ELASTICSEARCH_VERSION}..."
    cat >> "$ROOT_DIR/docker-compose.dynamic.yml" << EOF
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTICSEARCH_VERSION}
    container_name: stackored-elasticsearch
    restart: unless-stopped
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      - stackored-net

EOF
fi

# Mailhog
if is_enabled "ENABLE_MAILHOG"; then
    echo -e "${BLUE}[INFO]${NC} Adding Mailhog..."
    cat >> "$ROOT_DIR/docker-compose.dynamic.yml" << EOF
  mailhog:
    image: mailhog/mailhog:${MAILHOG_VERSION}
    container_name: stackored-mailhog
    restart: unless-stopped
    ports:
      - "1025:1025"  # SMTP
      - "8025:8025"  # Web UI
    networks:
      - stackored-net

EOF
fi

###################################################################
# ADD NETWORK & VOLUMES
###################################################################

cat >> "$ROOT_DIR/docker-compose.dynamic.yml" << EOFNETWORK

networks:
  stackored-net:
    external: true

EOFNETWORK

# Add volumes section if any data services are enabled
VOLUMES_NEEDED=false
is_enabled "ENABLE_MYSQL" && VOLUMES_NEEDED=true
is_enabled "ENABLE_POSTGRES" && VOLUMES_NEEDED=true
is_enabled "ENABLE_MONGO" && VOLUMES_NEEDED=true
is_enabled "ENABLE_ELASTICSEARCH" && VOLUMES_NEEDED=true

if [ "$VOLUMES_NEEDED" = true ]; then
    cat >> "$ROOT_DIR/docker-compose.dynamic.yml" << EOFVOLUMES

volumes:
EOFVOLUMES
    
    is_enabled "ENABLE_MYSQL" && echo "  mysql-data:" >> "$ROOT_DIR/docker-compose.dynamic.yml"
    is_enabled "ENABLE_POSTGRES" && echo "  postgres-data:" >> "$ROOT_DIR/docker-compose.dynamic.yml"
    is_enabled "ENABLE_MONGO" && echo "  mongo-data:" >> "$ROOT_DIR/docker-compose.dynamic.yml"
    is_enabled "ENABLE_ELASTICSEARCH" && echo "  elasticsearch-data:" >> "$ROOT_DIR/docker-compose.dynamic.yml"
fi

###################################################################
# CREATE NETWORK IF NOT EXISTS
###################################################################
echo -e "${BLUE}[INFO]${NC} Ensuring Docker network exists..."
docker network inspect stackored-net >/dev/null 2>&1 || docker network create stackored-net

###################################################################
# SUMMARY
###################################################################
echo ""
echo -e "${GREEN}[SUCCESS]${NC} Stackored generation completed!"
echo ""
echo "Generated files:"
echo "  - stackored.yml (base compose)"
echo "  - docker-compose.dynamic.yml (dynamic services)"
echo ""
echo "Enabled services:"
is_enabled "ENABLE_MYSQL" && echo "  ✓ MySQL ${MYSQL_VERSION}"
is_enabled "ENABLE_REDIS" && echo "  ✓ Redis ${REDIS_VERSION}"
is_enabled "ENABLE_POSTGRES" && echo "  ✓ PostgreSQL ${POSTGRES_VERSION}"
is_enabled "ENABLE_MONGO" && echo "  ✓ MongoDB ${MONGO_VERSION}"
is_enabled "ENABLE_MEMCACHED" && echo "  ✓ Memcached ${MEMCACHED_VERSION}"
is_enabled "ENABLE_RABBITMQ" && echo "  ✓ RabbitMQ ${RABBITMQ_VERSION}"
is_enabled "ENABLE_ELASTICSEARCH" && echo "  ✓ Elasticsearch ${ELASTICSEARCH_VERSION}"
is_enabled "ENABLE_MAILHOG" && echo "  ✓ Mailhog"
echo ""
echo "Next steps:"
echo "  ./cli/stackored up     # Start all services"
echo "  ./cli/stackored ps     # Check running services"
echo ""
