#!/usr/bin/env php
<?php

require __DIR__ . '/lib/FileSystem.php';
require __DIR__ . '/lib/Logger.php';
require __DIR__ . '/lib/EnvLoader.php';
require __DIR__ . '/lib/ProjectLoader.php';
require __DIR__ . '/lib/TemplateEngine.php';
require __DIR__ . '/lib/ComposeBuilder.php';
require __DIR__ . '/lib/Generator.php';

$generator = new \Stackored\CLI\Generator();
$generator->run();
